### ISSUE TITLE
You tried

### ISSUE THREAD

**Issue by pie-flavor** [MatrixDevTeam/LavaBukkit#30]
Licensing progress:

- [x] Minecraft (duh, but also under MCP's license)
- [x] Forge (LGPL)
- [x] Bukkit (LGPL)
- [x] Spigot / CB (CC-BY-SA)
- [x] MCP (custom)
- [x] IBXM (new BSD)

You should probably get the rest of these before you get DMCAed. Lord knows what prevents you from just using .patch files like Forge does.

**Comment by GMatrixGames** [comment]
IBXM is located in the licenses already, but all are now in the License folder

**Comment by pie-flavor** [comment]
You can't just copy-paste the licenses and call it done. Bukkit's not even GPL - it's LGPL. You don't have Spigot's in yet. And you're directly in violation of MCP's - `- Release the decompiled source code of Minecraft in any way.`

**Comment by GMatrixGames** [comment]
If you want to be a prick about this, go to the other ones that are more popular than ours.
