### ISSUE TITLE
Release LavaBukkit, It is now building (Optional)

### ISSUE THREAD

**Issue by josephworks** [MatrixDevTeam/LavaBukkit#57]

**Comment by GMatrixGames** [comment]
What you do mean by "Release"?

**Comment by josephworks** [comment]
There are only 2 releases

Joseph R.

**Comment by josephworks** [comment]
Lavabukkit/Releases

Joseph R.

**Comment by GMatrixGames** [comment]
I only post a release when there is a big change, otherwise, people can get a build from Jenkins (when I set that up)

**Comment by josephworks** [comment]
Ok sounds good / close issue

Joseph R.
