### ISSUE TITLE
Problem with multiple worlds

### ISSUE THREAD

**Issue by EvilShark25** [MatrixDevTeam/LavaBukkit#78]
Hello I have some problems with multiple MultiWorld plugins.
I tried the famous MultiverseCore plugin and created an own simple world loading plugin.
Code to load the world: (Bukkit) Bukkit.getServer().createWorld(new WorldCreator("WORLD_NAME"));

And with both plugins I get the following error: java.lang.IllegalArgumentException: Could not get provider type for dimension 13, does not exist [...]

I think this issue is related to Forge because Forge also loads the main world while starting the server but I only know the Bukkit-API so it would be nice if anybody could help me out.

**Comment by GMatrixGames** [comment]
This issue will be fixed with the next big update, there's an issue with dimension loading that was already brought to my attention in testing.

**Comment by EvilShark25** [comment]
ok nice to hear that!
