### ISSUE TITLE
Delete https://github.com/MatrixDevTeam/LavaBukkit/tree/db72b972bfc86bf27b1e18b6d6c6f694381ebce3/buildSrc/build/reports/task-properties

### ISSUE THREAD

**Issue by josephworks** [MatrixDevTeam/LavaBukkit#83]
Useless dir and contains the word **`Atom`**

**Comment by josephworks** [comment]
https://github.com/MatrixDevTeam/LavaBukkit/tree/db72b972bfc86bf27b1e18b6d6c6f694381ebce3/buildSrc/build/reports/task-properties

**Comment by GMatrixGames** [comment]
I will make a .gitignore entry, thank you.

**Comment by josephworks** [comment]
Ok, sounds good

Joseph R.
